### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by emmatyping** [coreylowman/ragz#1]
Hi! I am interested in writing an AlphaZero based agent in Rust. This project appears to be pretty well fleshed out and I figured I might be able to re-use the `synthesis` package for my agent. Would you be willing to release this code under an MIT or Apache style license?

**Comment by chelsea0x3b** [comment]
@ethanhs thanks for asking! Just added dual MIT & apache licenses

**Comment by emmatyping** [comment]
Thanks!
